#include "rage.hpp"

instruc_t Instructions[] =
{
	{ "NOP", 	0},
	{ "IADD", 	0},
	{ "ISUB", 	0},
	{ "IMUL", 	0},
	{ "IDIV", 	0},
	{ "IMOD", 	0},
	{ "INOT", 	0},
	{ "INEG", 	0},
	{ "IEQ", 	0},
	{ "INE", 	0},
	{ "IGT", 	0},
	{ "IGE", 	0},
	{ "ILT", 	0},
	{ "ILE", 	0},
	{ "FADD", 	0},
	{ "FSUB", 	0},
	{ "FMUL", 	0},
	{ "FDIV", 	0},
	{ "FMOD", 	0},
	{ "FNEG", 	0},
	{ "FEQ", 	0},
	{ "FNE", 	0},
	{ "FGT", 	0},
	{ "FGE", 	0},
	{ "FLT", 	0},
	{ "FLE", 	0},
	{ "VADD", 	0},
	{ "VSUB", 	0},
	{ "VMUL", 	0},
	{ "VDIV", 	0},
	{ "VNEG", 	0},
	{ "IAND", 	0},
	{ "IOR", 	0},
	{ "IXOR", 	0},
	{ "I2F", 	0},
	{ "F2I", 	0},
	{ "F2V", 	0},
	{ "PUSH U8", 	0},
	{ "PUSH U8 U8", 	0},
	{ "PUSH U8 U8 U8", 	0},
	{ "PUSH U32", 	0},
	{ "PUSHF", 	0},
	{ "DUP", 	0},
	{ "DROP", 	0},
	{ "NATIVE", 0},
	{ "ENTER", 	0 },
	{ "LEAVE", 	CF_STOP },
	{ "LOAD", 	0},
	{ "STORE", 	0},
	{ "STORE_REV", 	0},
	{ "LOAD_N", 	0},
	{ "STORE_N", 	0},
	{ "ARRAY_U8", 	0},
	{ "ARRAY_U8_LOAD", 	0},
	{ "ARRAY_U8_STORE", 	0},
	{ "LOCAL_U8", 	0},
	{ "LOCAL_U8_LOAD", 	0},
	{ "LOCAL_U8_STORE", 	0},
	{ "STATIC_U8", 	0},
	{ "STATIC_U8_LOAD", 	0},
	{ "STATIC_U8_STORE", 	0},
	{ "IADD_U8", 	0},
	{ "IMUL_U8", 	0},
	{ "IOFFSET", 	0},
	{ "IOFFSET_U8", 	0},
	{ "IOFFSET_U8_LOAD", 	0},
	{ "IOFFSET_U8_STORE", 	0},
	{ "PUSH_CONST_S16", 	0},
	{ "IADD_S16", 	0},
	{ "IMUL_S16", 	0},
	{ "IOFFSET_S16", 	0},
	{ "IOFFSET_S16_LOAD", 	0},
	{ "IOFFSET_S16_STORE", 	0},
	{ "ARRAY_U16", 	0},
	{ "ARRAY_U16_LOAD", 	0},
	{ "ARRAY_U16_STORE", 	0},
	{ "LOCAL_U16", 	0},
	{ "LOCAL_U16_LOAD", 	0},
	{ "LOCAL_U16_STORE", 	0},
	{ "STATIC_U16", 	0},
	{ "STATIC_U16_LOAD", 	0},
	{ "STATIC_U16_STORE", 	0},
	{ "GLOBAL_U16", 	0},
	{ "GLOBAL_U16_LOAD", 	0},
	{ "GLOBAL_U16_STORE", 	0},
	{ "J", 	CF_USE1 | CF_JUMP },
	{ "JZ", 	CF_USE1 | CF_JUMP },
	{ "IEQ_JZ", 	CF_USE1 | CF_JUMP },
	{ "INE_JZ", 	CF_USE1 | CF_JUMP },
	{ "IGT_JZ", 	CF_USE1 | CF_JUMP },
	{ "IGE_JZ", 	CF_USE1 | CF_JUMP },
	{ "ILT_JZ", 	CF_USE1 | CF_JUMP },
	{ "ILE_JZ", 	CF_USE1 | CF_JUMP },
	{ "CALL", 	CF_USE1 | CF_CALL },
	{ "GLOBAL_U24", 	0},
	{ "GLOBAL_U24_LOAD", 	0},
	{ "GLOBAL_U24_STORE", 	0},
	{ "PUSH_CONST_U24", 	0},
	{ "SWITCH", 	0},
	{ "STRING", 	0},
	{ "STRINGHASH", 	0},
	{ "TEXT_LABEL_ASSIGN_STRING", 	0},
	{ "TEXT_LABEL_ASSIGN_INT", 	0},
	{ "TEXT_LABEL_APPEND_STRING", 	0},
	{ "TEXT_LABEL_APPEND_INT", 	0},
	{ "TEXT_LABEL_COPY", 	0},
	{ "CATCH", 	0},
	{ "THROW", 	0},
	{ "CALLINDIRECT", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSH", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF", 	0},
	{ "PUSHF",		0 }
};

CASSERT(qnumber(Instructions) == RAGE_last);
